version: "3.8"
services:
  app:
    container_name: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin-pw
      - MARIADB_USER=todo-admin
      - MARIADB_PASSWORD=admin-pw
      - MARIADB_DATABASE=tododot
    ports:
      - "3306:3306"

volumes:
  db_data:
